Feature/typography
deboraCs26/desafio-front-taqtile pull request #2
Opened 2023-08-29 20:09 UTC by deboraCs26

![image](https://github.com/deboraCs26/desafio-front-taqtile/assets/119463609/0604b2f6-4a7c-4517-8552-d3a080ac8596)

2023-08-30 14:14 UTC, Japoncio3k requested changes
Tem que usar styled components pra criar os componentes estilizados!

2023-09-06 11:01 UTC, Japoncio3k commented on src/typography/body2/style.tsx
> +export const StyledBody2 = styled.div<Body2Props>`
Não devia ser uma tag de texto? acho que `div` não combina mt bem aqui

2023-09-06 15:44 UTC, deboraCs26 commented on src/typography/body2/style.tsx
> +export const StyledBody2 = styled.div<Body2Props>`
vou corrigir

2023-09-11 11:56 UTC, Japoncio3k approved these changes

2023-09-11 11:56 UTC, Japoncio3k commented on src/typography/body2/style.tsx
> +  font-size: ${(props) => (props.size === 'large' ? typography.fontSize.large : typography.fontSize.small)};
Dá pra criar uma interface e adicionar o tipo de `props` aqui pra não precisar usar o `props.color as Colors`
```suggestion
  font-size: ${(props: StyledBody2Props) => (props.size === 'large' ? typography.fontSize.large : typography.fontSize.small)};
```

2023-09-14 12:36 UTC, Japoncio3k commented on src/typography/body1/index.tsx
> +);
vc não precisa fazer esse componente Body1, pode mudar o nome do `StyledBody1` pra `Body1` e usar ele direto

2023-09-14 12:36 UTC, Japoncio3k commented on src/typography/body2/index.tsx
> +export const Body2 = ({ children, weight, color, height, size }: Body2Props) => (
o mesmo serve pra todos os componentes que seguem esse formato 
`<Styled>
{children}
</Styled>`

2023-09-14 12:36 UTC, Japoncio3k commented on src/typography/h4/style.tsx
> +      : colors.base.gray};
É interessante usar o ternário quando for um if só
Quando são mais condições fica confuso de ler e é interessante criar uma função que retorne os valores

2023-09-14 12:36 UTC, Japoncio3k commented on src/typography/price/style.tsx
> +      : typography.fontWeight.regular};
Mesma coisa aqui

2023-10-18 01:09 UTC, merged